export const popularitem=[
    {
        id:1,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:22.50,
    },
    {
        id:2,
        avatar:"https://m.media-amazon.com/images/I/81NYE4eC+xL._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:40,
    },
    {
        id:3,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Under Armour",
        name:"Raid 2.0 shorts",
        price:22.63,
    },
    {
        id:4,
        avatar:"https://m.media-amazon.com/images/I/71rQq8PIULL._AC_SX255_.jpg",
        number:2255,
        brand:"Under Armour",
        name:"Raid 2.0 shorts",
        price:22.63,
    },
    {
        id:5,
        avatar:"https://m.media-amazon.com/images/I/81j8hvSmu7L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein",
        name:"Men's Cotton Classics Megapack Boxer Briefs",
        price:59.50,
    },
    {
        id:6,
        avatar:"https://m.media-amazon.com/images/I/81bdJtidxtL._AC_SX255_.jpg",
        number:506,
        brand:"Levi's® Womens",
        name:"501® High-Rise Shorts",
        price:49.99,
    },
    {
        id:7,
        avatar:"https://m.media-amazon.com/images/I/81bdJtidxtL._AC_SX255_.jpg",
        number:506,
        brand:"Levi's® Womens",
        name:"501® High-Rise Shorts",
        price:49.99,
    },
    {
        id:8,
        avatar:"https://m.media-amazon.com/images/I/812dWoLYTeL._AC_SX255_.jpg",
        number:228,
        brand:"Under Armour",
        name:"UA Tech 1/2 Zip",
        price:28.09,
    },
    {
        id:9,
        avatar:"https://m.media-amazon.com/images/I/61OB1zpc5WL._AC_SX255_.jpg",
        number:14,
        brand:"Under Armour",
        name:"UA Tech 1/2 Zip",
        price:28.09,
    },
    {
        id:10,
        avatar:"https://m.media-amazon.com/images/I/61TKFhh1HnL._AC_SX255_.jpg",
        number:14,
        brand:"Under Armour",
        name:"UA Tech 1/2 Zip",
        price:30.09,
    },
    {
        id:11,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },
    {
        id:12,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },
    {
        id:13,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },
    {
        id:14,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },
    {
        id:15,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },
    {
        id:16,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },
    {
        id:17,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },
    {
        id:18,
        avatar:"https://m.media-amazon.com/images/I/91NlHmHtP1L._AC_SX255_.jpg",
        number:2255,
        brand:"Calvin Klein Underwear",
        name:"Modern Cotton Bralette F3785",
        price:"$22.50",
    },

]