export const products=[
    {
        id:"1",
        avatar:"https://m.media-amazon.com/images/G/01/2020/trendingbrandlogos/KEEN-LOGO.jpg"
    },
    {
        id:"2",
        avatar:"https://m.media-amazon.com/images/G/01/2020/trendingbrandlogos/brooks-brand-index-logo.jpg"
    },
    {
        id:"3",
        avatar:"https://m.media-amazon.com/images/G/01/2020/trendingbrandlogos/crocs-brand-index-logo.jpg"
    },
    {
        id:"4",
        avatar:"https://m.media-amazon.com/images/G/01/2020/trendingbrandlogos/birkenstock-brand-index-logo.jpg"
    },
    {
        id:"5",
        avatar:"https://m.media-amazon.com/images/G/01/2020/trendingbrandlogos/new-balance-brand-index-logo.jpg"
    },
    {
        id:"6",
        avatar:"https://m.media-amazon.com/images/G/01/2020/trendingbrandlogos/hoka-brand-index-logo.jpg"
    },
    {
        id:"7",
        avatar:"https://m.media-amazon.com/images/G/01/2021/brandindex/adidas-brand-index-logo.jpg"
    },
    {
        id:"8",
        avatar:"https://m.media-amazon.com/images/G/01/2020/trendingbrandlogos/native-brand-index.jpg"
    }
]